# Generated by Django 3.0.5 on 2021-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=1000)),
                ('Experiance', models.CharField(max_length=1000)),
                ('Jobtype', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('Link', models.CharField(max_length=1000)),
            ],
        ),
    ]
